### ISSUE TITLE
apinger fails after a while

### ISSUE THREAD

**Issue by oparoz** [opnsense/apinger#3]
After a while apinger silently fails and needs to be restarted. This has been going on for a while and is still a problem on 16.1.6

```
Jun 10 15:27:00 apinger: command (al/opnsense/service/configd_ctl.py -m 'dyndns reload VPN_TCP_VPNV4' 'ipsecdns reload' 'openvpn reload VPN_TCP_VPNV4' 'filter reload' ) exited with status: 127
Jun 10 15:27:00 apinger: Error while starting command form alarm(down) on target(8.8.8.8-VPN_TCP2_VPNV4)
```

**Comment by fichtner** [comment]
I think that subst_macros() causes this as it rewrites the command prior to invoke.

**Comment by fichtner** [comment]
Can you try this version?

    # pkg add -f https://pkg.opnsense.org/snapshots/apinger-0.7_1.txz

**Comment by fichtner** [comment]
Better this one ;)

    # # pkg add -f https://pkg.opnsense.org/snapshots/apinger-0.7_2.txz

**Comment by oparoz** [comment]
Installed and restarted the service. I'll keep you posted. Thank you.

**Comment by oparoz** [comment]
The fix doesn't seem to work. I don't see the mangled command any more, but whenever tier1 fails, the connection is not switched to tier2. Seems to work better with the version from 16.1.17

**Comment by fichtner** [comment]
Sounds like the right direction... will have another patch later this week. RC release comes first, the commits for this ticket will not be shipped.

**Comment by oparoz** [comment]
OK

**Comment by reetp** [comment]
Any further fixes on this Franco ? On my 16.7 with 3 WANs it is unusable.

The two main WAN interfaces are in a 'Active True IP' on separate Draytek 2820s (I can't do passthrough on these) - the Drayteks hand the public IP to the WAN interface of Opnsense.

The 3rd is a backup long range Wifi connection.

apinger to the two main connections fails after 10 seconds of a restart and the connection falls back to the Wifi connection. Strangely the double natted DHCP Wifi connection is always fine......

As a result I can't use gateway monitoring at all and as a result, gateway groups. Back to my old setup for now :-(

Aug 11 01:57:30 OPNsense apinger: Starting Alarm Pinger, apinger(40399)
Aug 11 01:57:40 OPNsense apinger: ALARM: WAN1_DHCP(4.4.4.4)  *** down ***
Aug 11 01:57:40 OPNsense apinger: ALARM: WAN2_DHCP(8.8.8.8)  *** down ***
Aug 11 02:00:27 OPNsense apinger: SIGHUP received, reloading configuration.
Aug 11 02:05:07 OPNsense apinger: Exiting on signal 15.
Aug 11 02:05:08 OPNsense apinger: Starting Alarm Pinger, apinger(12204)
Aug 11 02:05:18 OPNsense apinger: ALARM: WAN1_DHCP(4.4.4.4)  *** down ***
Aug 11 02:05:18 OPNsense apinger: ALARM: WAN2_DHCP(8.8.8.8)  *** down ***

Happy to test anything

**Comment by fichtner** [comment]
No news at this point. I had to revert the post-0.7 changes, starting fresh on 0.8

**Comment by fichtner** [comment]
Now I got confused, @reetp your issue is likely #2

**Comment by fichtner** [comment]
dpinger should perform better. apinger is going away in 2019.
